name: Formato (Lint)

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linter
        run: pip install black

      - name: Run Black
        run: black --check .
